services:
    case_store_case_study_field_type_integer.type:
        class: CaseStoreCaseStudyFieldTypeIntegerBundle\Service\CaseStoreFieldTypeIntegerService
        arguments: ["@service_container"]
        tags:
          -  { name: case_study_field_type.definition }
