################################################### Home

case_store_homepage:
    path:     /
    defaults: { _controller: CaseStoreBundle:Default:index }

case_store_homepage_projects:
    path:     /project
    defaults: { _controller: CaseStoreBundle:Default:project }

case_store_newproject:
    path:     /newproject
    defaults: { _controller: CaseStoreBundle:ProjectNew:index }

################################################### Project

case_store_project:
    path:     /project/{projectId}
    defaults: { _controller: CaseStoreBundle:Project:index }


case_store_project_map:
    path:     /project/{projectId}/map
    defaults: { _controller: CaseStoreBundle:Project:map }

case_store_project_map_data_json:
    path:     /project/{projectId}/mapData.json
    defaults: { _controller: CaseStoreBundle:Project:mapDataJSON }


case_store_project_my_case_studies:
    path:     /project/{projectId}/mycasestudies
    defaults: { _controller: CaseStoreBundle:Project:myCaseStudies }

case_store_project_case_studies:
    path:     /project/{projectId}/casestudies
    defaults: { _controller: CaseStoreBundle:Project:caseStudies }

case_store_project_case_studies_search:
    path:     /project/{projectId}/casestudiessearch
    defaults: { _controller: CaseStoreBundle:Project:caseStudiesSearch }


case_store_project_case_study_select_field:
    path:     /project/{projectId}/casestudyselectfield/{fieldId}
    defaults: { _controller: CaseStoreBundle:ProjectCaseStudyField:selectField }

case_store_project_case_study_select_field_option:
    path:     /project/{projectId}/casestudyselectfield/{fieldId}/option/{optionId}
    defaults: { _controller: CaseStoreBundle:ProjectCaseStudyField:selectFieldOption }


case_store_project_outputs:
    path:     /project/{projectId}/outputs
    defaults: { _controller: CaseStoreBundle:Project:outputs }



case_store_new_case_study:
    path:     /project/{projectId}/newcasestudy
    defaults: { _controller: CaseStoreBundle:CaseStudyNew:index }

case_store_new_output:
    path:     /project/{projectId}/newoutput
    defaults: { _controller: CaseStoreBundle:OutputNew:newOutput }

################################################### Project Admin

case_store_project_admin:
    path:     /project/{projectId}/admin
    defaults: { _controller: CaseStoreBundle:ProjectAdmin:index }


case_store_project_admin_case_study_field_definitions:
    path:     /project/{projectId}/admin/casestudyfielddefinitions
    defaults: { _controller: CaseStoreBundle:ProjectAdmin:caseStudyFieldDefinitions }

case_store_project_admin_new_case_study_field_definition:
    path:     /project/{projectId}/admin/newcasestudyfielddefinition
    defaults: { _controller: CaseStoreBundle:ProjectAdminCaseStudyFieldDefinitionNew:index }


case_store_project_admin_case_study_field_definition:
    path:     /project/{projectId}/admin/casestudyfielddefinition/{caseStudyFieldDefinitionId}
    defaults: { _controller: CaseStoreBundle:ProjectAdminCaseStudyFieldDefinition:index }

case_store_project_admin_case_study_field_definition_new_option:
    path:     /project/{projectId}/admin/casestudyfielddefinition/{caseStudyFieldDefinitionId}/newoption
    defaults: { _controller: CaseStoreBundle:ProjectAdminCaseStudyFieldDefinition:newOption }


case_store_project_admin_output_field_definitions:
    path:     /project/{projectId}/admin/outputfielddefinitions
    defaults: { _controller: CaseStoreBundle:ProjectAdmin:outputFieldDefinitions }

case_store_project_admin_new_output_field_definition:
    path:     /project/{projectId}/admin/newoutputfielddefinition
    defaults: { _controller: CaseStoreBundle:ProjectAdminOutputFieldDefinitionNew:index }


case_store_project_admin_output_field_definition:
    path:     /project/{projectId}/admin/outputfielddefinition/{outputFieldDefinitionId}
    defaults: { _controller: CaseStoreBundle:ProjectAdminOutputFieldDefinition:index }

################################################### Case Study

case_store_case_study:
    path:     /project/{projectId}/casestudy/{caseStudyId}
    defaults: { _controller: CaseStoreBundle:CaseStudy:index }

case_store_case_study_document_download:
    path:     /project/{projectId}/casestudy/{caseStudyId}/document/{documentId}
    defaults: { _controller: CaseStoreBundle:CaseStudy:documentDownload }

################################################### Case Study - Edit Project

case_store_case_study_new_comment:
    path:     /project/{projectId}/casestudy/{caseStudyId}/newcomment
    defaults: { _controller: CaseStoreBundle:CaseStudy:newComment }

################################################### Case Study  - Edit Case Study

case_store_case_study_edit_users:
    path:     /project/{projectId}/casestudy/{caseStudyId}/edit/users
    defaults: { _controller: CaseStoreBundle:CaseStudyEdit:editUsers }

case_store_case_study_edit_locations:
    path:     /project/{projectId}/casestudy/{caseStudyId}/edit/locations
    defaults: { _controller: CaseStoreBundle:CaseStudyEdit:editLocations }

case_store_case_study_edit_field:
    path:     /project/{projectId}/casestudy/{caseStudyId}/edit/field/{fieldDefinitionId}
    defaults: { _controller: CaseStoreBundle:CaseStudyEdit:editField }

case_store_case_study_new_document:
    path:     /project/{projectId}/casestudy/{caseStudyId}/newdocument
    defaults: { _controller: CaseStoreBundle:CaseStudyEdit:newDocument }

case_store_case_study_link_output:
    path:     /project/{projectId}/casestudy/{caseStudyId}/linkOutput
    defaults: { _controller: CaseStoreBundle:CaseStudyEdit:linkOutput }

################################################### Output

case_store_output:
    path:     /project/{projectId}/output/{outputId}
    defaults: { _controller: CaseStoreBundle:Output:index }

case_store_output_document_download:
    path:     /project/{projectId}/output/{outputId}/document/{documentId}
    defaults: { _controller: CaseStoreBundle:Output:documentDownload }

################################################### Output - Edit

case_store_output_edit_field:
    path:     /project/{projectId}/output/{outputId}/edit/field/{fieldDefinitionId}
    defaults: { _controller: CaseStoreBundle:OutputEdit:editField }

case_store_output_new_document:
    path:     /project/{projectId}/output/{outputId}/newdocument
    defaults: { _controller: CaseStoreBundle:OutputEdit:newDocument }

case_store_output_link_case_study:
    path:     /project/{projectId}/output/{outputId}/linkcasestudy
    defaults: { _controller: CaseStoreBundle:OutputEdit:linkCaseStudy }


################################################### User Account

case_store_you:
    pattern:  /you
    defaults: { _controller: CaseStoreBundle:Default:you }
    methods:  [GET]