services:

    app.project_voter:
        class: CaseStoreBundle\Security\ProjectVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.case_study_voter:
        class: CaseStoreBundle\Security\CaseStudyVoter
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.output_voter:
        class: CaseStoreBundle\Security\OutputVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    pre_persist.listener:
        class: CaseStoreBundle\EventListener\PrePersistEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    case_study_field_type_finder:
        class: CaseStoreBundle\Service\CaseStudyFieldTypeFinderService
        arguments: ["@service_container"]
