security:
  encoders:
    CaseStoreBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
       our_db_provider:
            entity:
                class: CaseStoreBundle:User
                property: email

  firewalls:
    main:
      pattern: ^/
      provider: our_db_provider
      anonymous: ~
      form_login:
          login_path: case_store_login
          check_path: case_store_login
      logout:
          path:   /logout
          target: /



  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/newproject, role: IS_AUTHENTICATED_FULLY }
    - { path: ^/youraccount, role: IS_AUTHENTICATED_FULLY }

