services:
    case_store_case_study_field_type_string.type:
        class: CaseStoreCaseStudyFieldTypeStringBundle\Service\CaseStoreFieldTypeStringService
        arguments: ["@service_container"]
        tags:
          -  { name: case_study_field_type.definition }
