services:
    case_store_case_study_field_type_text.type:
        class: CaseStoreCaseStudyFieldTypeTextBundle\Service\CaseStoreFieldTypeTextService
        arguments: ["@service_container"]
        tags:
          -  { name: case_study_field_type.definition }
