services:
    case_store_case_study_field_type_select.type:
        class: CaseStoreCaseStudyFieldTypeSelectBundle\Service\CaseStoreFieldTypeSelectService
        arguments: ["@service_container"]
        tags:
          -  { name: case_study_field_type.definition }
